### ISSUE TITLE
AMASS dataset download

### ISSUE THREAD

**Issue by heduo-star** [dulucas/siMLPe#1]
@dulucas 
Dear author, 
Can you attach the format and link to download the AMASS dataset？
Thank you very much!

![image](https://user-images.githubusercontent.com/83168856/182024001-2f000085-e2b9-4382-83c7-3e2dc20dfbf7.png)
I don't know which one to download.

**Comment by dulucas** [comment]
To download the AMASS dataset, you need to download it manually, because it needs a personal account and sign a non commercial contract. We can just provide a list of used datasets [here](https://github.com/dulucas/siMLPe/blob/main/data/amass_train.txt) and [here](https://github.com/dulucas/siMLPe/blob/main/data/amass_test.txt). And you should download the SMPL+H G.

**Comment by heduo-star** [comment]
> To download the AMASS dataset, you need to download it manually, because it needs a personal account and sign a non commercial contract. We can just provide a list of used datasets [here](https://github.com/dulucas/siMLPe/blob/main/data/amass_train.txt) and [here](https://github.com/dulucas/siMLPe/blob/main/data/amass_test.txt). And you should download the SMPL+H G.

Thank you very much!

**Comment by heduo-star** [comment]
> To download the AMASS dataset, you need to download it manually, because it needs a personal account and sign a non commercial contract. We can just provide a list of used datasets [here](https://github.com/dulucas/siMLPe/blob/main/data/amass_train.txt) and [here](https://github.com/dulucas/siMLPe/blob/main/data/amass_test.txt). And you should download the SMPL+H G.

Thank you very much!

**Comment by Deante-dx** [comment]
The test dataset of AMASS(BioMotionLab_NTroje) can't find in [AMASS](https://amass.is.tue.mpg.de/download.php)

**Comment by dulucas** [comment]
It's [BMLrub](https://www.biomotionlab.ca/)

**Comment by Deante-dx** [comment]
> It's [BMLrub](https://www.biomotionlab.ca/)

Thank you
