### ISSUE TITLE
Reproduction on the H36M dataset

### ISSUE THREAD

**Issue by marcocasarin** [dulucas/siMLPe#12]
Hi! I have been attempting to reproduce your paper results on the H36M dataset. I have followed the instruction on the README and the discussion on [this](https://github.com/dulucas/siMLPe/issues/9) issue to evaluate the checkpoint you provided on the H36M dataset. However, with reference to Table 1 in your paper, I'm not getting the same results: 
- My evaluation results: [13.4, 24.0, 47.7, 58.4, 78.6, 92.1, 105.2, 112.0]
- Paper evaluation results: [9.6, 21.7, 46.3, 57.3, 75.7, 90.1, 101.8, 109.4]

Moreover, I have also implemented the _Repeating Last-Frame_ baseline with simple changes in the same _test.py_ script for the evaluation. This was to make sure the dataset I am loading is correct. I got the exact same results as in your paper.

Is there something I'm missing? Maybe the checkpoint you provided in the repo is not the correct one to obtain the same results as in your paper. Should I train the model from scratch?

Thanks in advance for you help!

**Comment by Tong-Hao741** [comment]
我也遇到了相同的情况，请问你解决了吗？
I have also encountered the same situation. Have you resolved it？ T。T

**Comment by Tong-Hao741** [comment]
i train about 1000epoch , finall the result is keeping [12.7 28.9 62.3 76.2 97.6 111.9 122.1 127.7 ]

**Comment by marcocasarin** [comment]
I did not try to train the model from scratch, but I used the provided checkpoint to try to replicate the paper results (to avoid any randomness issue during training, like different seeds and related stuff). 
I have not solved the problem yet.

**Comment by Tong-Hao741** [comment]
ok fine ，thank u very much : )

**Comment by GUO-W** [comment]
Please see our answer here: https://github.com/dulucas/siMLPe/issues/13#issuecomment-2053990903. We train our model using the exact same scripts as in this repo, and uploaded the training details + checkpoints to this repo.

**Comment by marcocasarin** [comment]
It works, thanks!
