### ISSUE TITLE
The usage of ang2joint

### ISSUE THREAD

**Issue by BoruiHe** [dulucas/siMLPe#15]
Hi, I noticed that there is a function named ang2joint which was imported only when it came to the AMASS and 3DPW datasets. 

Based on my understanding, siMLPe requires a loss on velocities as part of its total loss. Since I am not familiar with these datasets, I guess the reason is these two datasets records joint angles (maybe angular velocity also) over time only and you need this function for further velocity loss calculation. Is that correct?

**Comment by dulucas** [comment]
That's correct!
