### ISSUE TITLE
use the STS-GCN evaluation method to calculate the MPJPE values for each dataset

### ISSUE THREAD

**Issue by Tong-Hao741** [dulucas/siMLPe#16]
Hello author, I would like to use the STS-GCN evaluation method to calculate the MPJPE values for each dataset. Can you provide the calculation code? I don't quite understand his calculation method and it seems that I haven't found the corresponding code in the repository. Thank you~

**Comment by dulucas** [comment]
We do not provide the evaluation code of STS-GCN and not plan to provide either. Their paper is doing unfair comparison with other papers and we do not want people of the community to follow their settings. We only did in our paper to clarify that with their settings, every paper could simply surpass their performance.

**Comment by dulucas** [comment]
We post in the issues of STS-GCN paper, but they deleted our posts and forced to close the issue(https://github.com/FraLuca/STSGCN/issues/12)

**Comment by Tong-Hao741** [comment]
Thank you for your prompt reply. I also noticed some clues about the data in the STS-GCN paper. It was only after reading # 12 you provided that I understood that an unfair comparison was made. Thank you again
