### ISSUE TITLE
Fail to load h36m_model_35000.pth

### ISSUE THREAD

**Issue by KD-NU** [dulucas/siMLPe#17]
Hi, dear authors. An error happens when I try to load the pretrained pth file in this repo. 

```
  File "test.py", line 112, in <module>
    model.load_state_dict(state_dict, strict=True)
```

The details are as following.

> RuntimeError: Error(s) in loading state_dict for siMLPe:
>         Missing key(s) in state_dict: "motion_mlp.mlps.0.fc0.fc.weight", "motion_mlp.mlps.0.fc0.fc.bias", "motion_mlp.mlps.0.norm0.alpha", "motion_mlp.mlps.0.norm0.beta", "motion_mlp.mlps.1.fc0.fc.weight", "motion_mlp.mlps.1.fc0.fc.bias", "motion_mlp.mlps.1.norm0.alpha", "motion_mlp.mlps.1.norm0.beta", "motion_mlp.mlps.2.fc0.fc.weight", "motion_mlp.mlps.2.fc0.fc.bias", "motion_mlp.mlps.2.norm0.alpha", "motion_mlp.mlps.2.norm0.beta", "motion_mlp.mlps.3.fc0.fc.weight", "motion_mlp.mlps.3.fc0.fc.bias", "motion_mlp.mlps.3.norm0.alpha", "motion_mlp.mlps.3.norm0.beta", "motion_mlp.mlps.4.fc0.fc.weight", "motion_mlp.mlps.4.fc0.fc.bias", "motion_mlp.mlps.4.norm0.alpha", "motion_mlp.mlps.4.norm0.beta", "motion_mlp.mlps.5.fc0.fc.weight", "motion_mlp.mlps.5.fc0.fc.bias", "motion_mlp.mlps.5.norm0.alpha", "motion_mlp.mlps.5.norm0.beta", "motion_mlp.mlps.6.fc0.fc.weight", "motion_mlp.mlps.6.fc0.fc.bias", "motion_mlp.mlps.6.norm0.alpha", "motion_mlp.mlps.6.norm0.beta", "motion_mlp.mlps.7.fc0.fc.weight", "motion_mlp.mlps.7.fc0.fc.bias", "motion_mlp.mlps.7.norm0.alpha", "motion_mlp.mlps.7.norm0.beta", "motion_mlp.mlps.8.fc0.fc.weight", "motion_mlp.mlps.8.fc0.fc.bias", "motion_mlp.mlps.8.norm0.alpha", "motion_mlp.mlps.8.norm0.beta", "motion_mlp.mlps.9.fc0.fc.weight", "motion_mlp.mlps.9.fc0.fc.bias", "motion_mlp.mlps.9.norm0.alpha", "motion_mlp.mlps.9.norm0.beta", "motion_mlp.mlps.10.fc0.fc.weight", "motion_mlp.mlps.10.fc0.fc.bias", "motion_mlp.mlps.10.norm0.alpha", "motion_mlp.mlps.10.norm0.beta", "motion_mlp.mlps.11.fc0.fc.weight", "motion_mlp.mlps.11.fc0.fc.bias", "motion_mlp.mlps.11.norm0.alpha", "motion_mlp.mlps.11.norm0.beta", "motion_mlp.mlps.12.fc0.fc.weight", "motion_mlp.mlps.12.fc0.fc.bias", "motion_mlp.mlps.12.norm0.alpha", "motion_mlp.mlps.12.norm0.beta", "motion_mlp.mlps.13.fc0.fc.weight", "motion_mlp.mlps.13.fc0.fc.bias", "motion_mlp.mlps.13.norm0.alpha", "motion_mlp.mlps.13.norm0.beta", "motion_mlp.mlps.14.fc0.fc.weight", "motion_mlp.mlps.14.fc0.fc.bias", "motion_mlp.mlps.14.norm0.alpha", "motion_mlp.mlps.14.norm0.beta", "motion_mlp.mlps.15.fc0.fc.weight", "motion_mlp.mlps.15.fc0.fc.bias", "motion_mlp.mlps.15.norm0.alpha", "motion_mlp.mlps.15.norm0.beta", "motion_mlp.mlps.16.fc0.fc.weight", "motion_mlp.mlps.16.fc0.fc.bias", "motion_mlp.mlps.16.norm0.alpha", "motion_mlp.mlps.16.norm0.beta", "motion_mlp.mlps.17.fc0.fc.weight", "motion_mlp.mlps.17.fc0.fc.bias", "motion_mlp.mlps.17.norm0.alpha", "motion_mlp.mlps.17.norm0.beta", "motion_mlp.mlps.18.fc0.fc.weight", "motion_mlp.mlps.18.fc0.fc.bias", "motion_mlp.mlps.18.norm0.alpha", "motion_mlp.mlps.18.norm0.beta", "motion_mlp.mlps.19.fc0.fc.weight", "motion_mlp.mlps.19.fc0.fc.bias", "motion_mlp.mlps.19.norm0.alpha", "motion_mlp.mlps.19.norm0.beta", "motion_mlp.mlps.20.fc0.fc.weight", "motion_mlp.mlps.20.fc0.fc.bias", "motion_mlp.mlps.20.norm0.alpha", "motion_mlp.mlps.20.norm0.beta", "motion_mlp.mlps.21.fc0.fc.weight", "motion_mlp.mlps.21.fc0.fc.bias", "motion_mlp.mlps.21.norm0.alpha", "motion_mlp.mlps.21.norm0.beta", "motion_mlp.mlps.22.fc0.fc.weight", "motion_mlp.mlps.22.fc0.fc.bias", "motion_mlp.mlps.22.norm0.alpha", "motion_mlp.mlps.22.norm0.beta", "motion_mlp.mlps.23.fc0.fc.weight", "motion_mlp.mlps.23.fc0.fc.bias", "motion_mlp.mlps.23.norm0.alpha", "motion_mlp.mlps.23.norm0.beta", "motion_mlp.mlps.24.fc0.fc.weight", "motion_mlp.mlps.24.fc0.fc.bias", "motion_mlp.mlps.24.norm0.alpha", "motion_mlp.mlps.24.norm0.beta", "motion_mlp.mlps.25.fc0.fc.weight", "motion_mlp.mlps.25.fc0.fc.bias", "motion_mlp.mlps.25.norm0.alpha", "motion_mlp.mlps.25.norm0.beta", "motion_mlp.mlps.26.fc0.fc.weight", "motion_mlp.mlps.26.fc0.fc.bias", "motion_mlp.mlps.26.norm0.alpha", "motion_mlp.mlps.26.norm0.beta", "motion_mlp.mlps.27.fc0.fc.weight", "motion_mlp.mlps.27.fc0.fc.bias", "motion_mlp.mlps.27.norm0.alpha", "motion_mlp.mlps.27.norm0.beta", "motion_mlp.mlps.28.fc0.fc.weight", "motion_mlp.mlps.28.fc0.fc.bias", "motion_mlp.mlps.28.norm0.alpha", "motion_mlp.mlps.28.norm0.beta", "motion_mlp.mlps.29.fc0.fc.weight", "motion_mlp.mlps.29.fc0.fc.bias", "motion_mlp.mlps.29.norm0.alpha", "motion_mlp.mlps.29.norm0.beta", "motion_mlp.mlps.30.fc0.fc.weight", "motion_mlp.mlps.30.fc0.fc.bias", "motion_mlp.mlps.30.norm0.alpha", "motion_mlp.mlps.30.norm0.beta", "motion_mlp.mlps.31.fc0.fc.weight", "motion_mlp.mlps.31.fc0.fc.bias", "motion_mlp.mlps.31.norm0.alpha", "motion_mlp.mlps.31.norm0.beta", "motion_mlp.mlps.32.fc0.fc.weight", "motion_mlp.mlps.32.fc0.fc.bias", "motion_mlp.mlps.32.norm0.alpha", "motion_mlp.mlps.32.norm0.beta", "motion_mlp.mlps.33.fc0.fc.weight", "motion_mlp.mlps.33.fc0.fc.bias", "motion_mlp.mlps.33.norm0.alpha", "motion_mlp.mlps.33.norm0.beta", "motion_mlp.mlps.34.fc0.fc.weight", "motion_mlp.mlps.34.fc0.fc.bias", "motion_mlp.mlps.34.norm0.alpha", "motion_mlp.mlps.34.norm0.beta", "motion_mlp.mlps.35.fc0.fc.weight", "motion_mlp.mlps.35.fc0.fc.bias", "motion_mlp.mlps.35.norm0.alpha", "motion_mlp.mlps.35.norm0.beta", "motion_mlp.mlps.36.fc0.fc.weight", "motion_mlp.mlps.36.fc0.fc.bias", "motion_mlp.mlps.36.norm0.alpha", "motion_mlp.mlps.36.norm0.beta", "motion_mlp.mlps.37.fc0.fc.weight", "motion_mlp.mlps.37.fc0.fc.bias", "motion_mlp.mlps.37.norm0.alpha", "motion_mlp.mlps.37.norm0.beta", "motion_mlp.mlps.38.fc0.fc.weight", "motion_mlp.mlps.38.fc0.fc.bias", "motion_mlp.mlps.38.norm0.alpha", "motion_mlp.mlps.38.norm0.beta", "motion_mlp.mlps.39.fc0.fc.weight", "motion_mlp.mlps.39.fc0.fc.bias", "motion_mlp.mlps.39.norm0.alpha", "motion_mlp.mlps.39.norm0.beta", "motion_mlp.mlps.40.fc0.fc.weight", "motion_mlp.mlps.40.fc0.fc.bias", "motion_mlp.mlps.40.norm0.alpha", "motion_mlp.mlps.40.norm0.beta", "motion_mlp.mlps.41.fc0.fc.weight", "motion_mlp.mlps.41.fc0.fc.bias", "motion_mlp.mlps.41.norm0.alpha", "motion_mlp.mlps.41.norm0.beta", "motion_mlp.mlps.42.fc0.fc.weight", "motion_mlp.mlps.42.fc0.fc.bias", "motion_mlp.mlps.42.norm0.alpha", "motion_mlp.mlps.42.norm0.beta", "motion_mlp.mlps.43.fc0.fc.weight", "motion_mlp.mlps.43.fc0.fc.bias", "motion_mlp.mlps.43.norm0.alpha", "motion_mlp.mlps.43.norm0.beta", "motion_mlp.mlps.44.fc0.fc.weight", "motion_mlp.mlps.44.fc0.fc.bias", "motion_mlp.mlps.44.norm0.alpha", "motion_mlp.mlps.44.norm0.beta", "motion_mlp.mlps.45.fc0.fc.weight", "motion_mlp.mlps.45.fc0.fc.bias", "motion_mlp.mlps.45.norm0.alpha", "motion_mlp.mlps.45.norm0.beta", "motion_mlp.mlps.46.fc0.fc.weight", "motion_mlp.mlps.46.fc0.fc.bias", "motion_mlp.mlps.46.norm0.alpha", "motion_mlp.mlps.46.norm0.beta", "motion_mlp.mlps.47.fc0.fc.weight", "motion_mlp.mlps.47.fc0.fc.bias", "motion_mlp.mlps.47.norm0.alpha", "motion_mlp.mlps.47.norm0.beta". 
>         Unexpected key(s) in state_dict: "motion_transformer.transformer.0.fc0.fc.weight", "motion_transformer.transformer.0.fc0.fc.bias", "motion_transformer.transformer.0.norm0.alpha", "motion_transformer.transformer.0.norm0.beta", "motion_transformer.transformer.1.fc0.fc.weight", "motion_transformer.transformer.1.fc0.fc.bias", "motion_transformer.transformer.1.norm0.alpha", "motion_transformer.transformer.1.norm0.beta", "motion_transformer.transformer.2.fc0.fc.weight", "motion_transformer.transformer.2.fc0.fc.bias", "motion_transformer.transformer.2.norm0.alpha", "motion_transformer.transformer.2.norm0.beta", "motion_transformer.transformer.3.fc0.fc.weight", "motion_transformer.transformer.3.fc0.fc.bias", "motion_transformer.transformer.3.norm0.alpha", "motion_transformer.transformer.3.norm0.beta", "motion_transformer.transformer.4.fc0.fc.weight", "motion_transformer.transformer.4.fc0.fc.bias", "motion_transformer.transformer.4.norm0.alpha", "motion_transformer.transformer.4.norm0.beta", "motion_transformer.transformer.5.fc0.fc.weight", "motion_transformer.transformer.5.fc0.fc.bias", "motion_transformer.transformer.5.norm0.alpha", "motion_transformer.transformer.5.norm0.beta", "motion_transformer.transformer.6.fc0.fc.weight", "motion_transformer.transformer.6.fc0.fc.bias", "motion_transformer.transformer.6.norm0.alpha", "motion_transformer.transformer.6.norm0.beta", "motion_transformer.transformer.7.fc0.fc.weight", "motion_transformer.transformer.7.fc0.fc.bias", "motion_transformer.transformer.7.norm0.alpha", "motion_transformer.transformer.7.norm0.beta", "motion_transformer.transformer.8.fc0.fc.weight", "motion_transformer.transformer.8.fc0.fc.bias", "motion_transformer.transformer.8.norm0.alpha", "motion_transformer.transformer.8.norm0.beta", "motion_transformer.transformer.9.fc0.fc.weight", "motion_transformer.transformer.9.fc0.fc.bias", "motion_transformer.transformer.9.norm0.alpha", "motion_transformer.transformer.9.norm0.beta", "motion_transformer.transformer.10.fc0.fc.weight", "motion_transformer.transformer.10.fc0.fc.bias", "motion_transformer.transformer.10.norm0.alpha", "motion_transformer.transformer.10.norm0.beta", "motion_transformer.transformer.11.fc0.fc.weight", "motion_transformer.transformer.11.fc0.fc.bias", "motion_transformer.transformer.11.norm0.alpha", "motion_transformer.transformer.11.norm0.beta", "motion_transformer.transformer.12.fc0.fc.weight", "motion_transformer.transformer.12.fc0.fc.bias", "motion_transformer.transformer.12.norm0.alpha", "motion_transformer.transformer.12.norm0.beta", "motion_transformer.transformer.13.fc0.fc.weight", "motion_transformer.transformer.13.fc0.fc.bias", "motion_transformer.transformer.13.norm0.alpha", "motion_transformer.transformer.13.norm0.beta", "motion_transformer.transformer.14.fc0.fc.weight", "motion_transformer.transformer.14.fc0.fc.bias", "motion_transformer.transformer.14.norm0.alpha", "motion_transformer.transformer.14.norm0.beta", "motion_transformer.transformer.15.fc0.fc.weight", "motion_transformer.transformer.15.fc0.fc.bias", "motion_transformer.transformer.15.norm0.alpha", "motion_transformer.transformer.15.norm0.beta", "motion_transformer.transformer.16.fc0.fc.weight", "motion_transformer.transformer.16.fc0.fc.bias", "motion_transformer.transformer.16.norm0.alpha", "motion_transformer.transformer.16.norm0.beta", "motion_transformer.transformer.17.fc0.fc.weight", "motion_transformer.transformer.17.fc0.fc.bias", "motion_transformer.transformer.17.norm0.alpha", "motion_transformer.transformer.17.norm0.beta", "motion_transformer.transformer.18.fc0.fc.weight", "motion_transformer.transformer.18.fc0.fc.bias", "motion_transformer.transformer.18.norm0.alpha", "motion_transformer.transformer.18.norm0.beta", "motion_transformer.transformer.19.fc0.fc.weight", "motion_transformer.transformer.19.fc0.fc.bias", "motion_transformer.transformer.19.norm0.alpha", "motion_transformer.transformer.19.norm0.beta", "motion_transformer.transformer.20.fc0.fc.weight", "motion_transformer.transformer.20.fc0.fc.bias", "motion_transformer.transformer.20.norm0.alpha", "motion_transformer.transformer.20.norm0.beta", "motion_transformer.transformer.21.fc0.fc.weight", "motion_transformer.transformer.21.fc0.fc.bias", "motion_transformer.transformer.21.norm0.alpha", "motion_transformer.transformer.21.norm0.beta", "motion_transformer.transformer.22.fc0.fc.weight", "motion_transformer.transformer.22.fc0.fc.bias", "motion_transformer.transformer.22.norm0.alpha", "motion_transformer.transformer.22.norm0.beta", "motion_transformer.transformer.23.fc0.fc.weight", "motion_transformer.transformer.23.fc0.fc.bias", "motion_transformer.transformer.23.norm0.alpha", "motion_transformer.transformer.23.norm0.beta", "motion_transformer.transformer.24.fc0.fc.weight", "motion_transformer.transformer.24.fc0.fc.bias", "motion_transformer.transformer.24.norm0.alpha", "motion_transformer.transformer.24.norm0.beta", "motion_transformer.transformer.25.fc0.fc.weight", "motion_transformer.transformer.25.fc0.fc.bias", "motion_transformer.transformer.25.norm0.alpha", "motion_transformer.transformer.25.norm0.beta", "motion_transformer.transformer.26.fc0.fc.weight", "motion_transformer.transformer.26.fc0.fc.bias", "motion_transformer.transformer.26.norm0.alpha", "motion_transformer.transformer.26.norm0.beta", "motion_transformer.transformer.27.fc0.fc.weight", "motion_transformer.transformer.27.fc0.fc.bias", "motion_transformer.transformer.27.norm0.alpha", "motion_transformer.transformer.27.norm0.beta", "motion_transformer.transformer.28.fc0.fc.weight", "motion_transformer.transformer.28.fc0.fc.bias", "motion_transformer.transformer.28.norm0.alpha", "motion_transformer.transformer.28.norm0.beta", "motion_transformer.transformer.29.fc0.fc.weight", "motion_transformer.transformer.29.fc0.fc.bias", "motion_transformer.transformer.29.norm0.alpha", "motion_transformer.transformer.29.norm0.beta", "motion_transformer.transformer.30.fc0.fc.weight", "motion_transformer.transformer.30.fc0.fc.bias", "motion_transformer.transformer.30.norm0.alpha", "motion_transformer.transformer.30.norm0.beta", "motion_transformer.transformer.31.fc0.fc.weight", "motion_transformer.transformer.31.fc0.fc.bias", "motion_transformer.transformer.31.norm0.alpha", "motion_transformer.transformer.31.norm0.beta", "motion_transformer.transformer.32.fc0.fc.weight", "motion_transformer.transformer.32.fc0.fc.bias", "motion_transformer.transformer.32.norm0.alpha", "motion_transformer.transformer.32.norm0.beta", "motion_transformer.transformer.33.fc0.fc.weight", "motion_transformer.transformer.33.fc0.fc.bias", "motion_transformer.transformer.33.norm0.alpha", "motion_transformer.transformer.33.norm0.beta", "motion_transformer.transformer.34.fc0.fc.weight", "motion_transformer.transformer.34.fc0.fc.bias", "motion_transformer.transformer.34.norm0.alpha", "motion_transformer.transformer.34.norm0.beta", "motion_transformer.transformer.35.fc0.fc.weight", "motion_transformer.transformer.35.fc0.fc.bias", "motion_transformer.transformer.35.norm0.alpha", "motion_transformer.transformer.35.norm0.beta", "motion_transformer.transformer.36.fc0.fc.weight", "motion_transformer.transformer.36.fc0.fc.bias", "motion_transformer.transformer.36.norm0.alpha", "motion_transformer.transformer.36.norm0.beta", "motion_transformer.transformer.37.fc0.fc.weight", "motion_transformer.transformer.37.fc0.fc.bias", "motion_transformer.transformer.37.norm0.alpha", "motion_transformer.transformer.37.norm0.beta", "motion_transformer.transformer.38.fc0.fc.weight", "motion_transformer.transformer.38.fc0.fc.bias", "motion_transformer.transformer.38.norm0.alpha", "motion_transformer.transformer.38.norm0.beta", "motion_transformer.transformer.39.fc0.fc.weight", "motion_transformer.transformer.39.fc0.fc.bias", "motion_transformer.transformer.39.norm0.alpha", "motion_transformer.transformer.39.norm0.beta", "motion_transformer.transformer.40.fc0.fc.weight", "motion_transformer.transformer.40.fc0.fc.bias", "motion_transformer.transformer.40.norm0.alpha", "motion_transformer.transformer.40.norm0.beta", "motion_transformer.transformer.41.fc0.fc.weight", "motion_transformer.transformer.41.fc0.fc.bias", "motion_transformer.transformer.41.norm0.alpha", "motion_transformer.transformer.41.norm0.beta", "motion_transformer.transformer.42.fc0.fc.weight", "motion_transformer.transformer.42.fc0.fc.bias", "motion_transformer.transformer.42.norm0.alpha", "motion_transformer.transformer.42.norm0.beta", "motion_transformer.transformer.43.fc0.fc.weight", "motion_transformer.transformer.43.fc0.fc.bias", "motion_transformer.transformer.43.norm0.alpha", "motion_transformer.transformer.43.norm0.beta", "motion_transformer.transformer.44.fc0.fc.weight", "motion_transformer.transformer.44.fc0.fc.bias", "motion_transformer.transformer.44.norm0.alpha", "motion_transformer.transformer.44.norm0.beta", "motion_transformer.transformer.45.fc0.fc.weight", "motion_transformer.transformer.45.fc0.fc.bias", "motion_transformer.transformer.45.norm0.alpha", "motion_transformer.transformer.45.norm0.beta", "motion_transformer.transformer.46.fc0.fc.weight", "motion_transformer.transformer.46.fc0.fc.bias", "motion_transformer.transformer.46.norm0.alpha", "motion_transformer.transformer.46.norm0.beta", "motion_transformer.transformer.47.fc0.fc.weight", "motion_transformer.transformer.47.fc0.fc.bias", "motion_transformer.transformer.47.norm0.alpha", "motion_transformer.transformer.47.norm0.beta".

Could you tell me how can I address this problem?

**Comment by dulucas** [comment]
replace "motion_transformer.transformer" by "motion_mlp.mlps" in the state_dict

**Comment by TUUFFY** [comment]
替换
model.load_state_dict(state_dict, strict=True)
为

state_dict = torch.load(args.model_pth, map_location="cpu")
converted_state_dict = {}
for k, v in state_dict.items():
    if k.startswith("motion_transformer.transformer"):
        new_k = k.replace("motion_transformer.transformer", "motion_mlp.mlps")
        converted_state_dict[new_k] = v
    else:
        converted_state_dict[k] = v  
model.load_state_dict(converted_state_dict, strict=True)
