### ISSUE TITLE
How to use the preditction model in real video?

### ISSUE THREAD

**Issue by Ninialover** [dulucas/siMLPe#19]
Hello!
I would like to use this model to predict my walking motion.If I want to complete the above task, do I need to convert the joint data in the video into other data formats (ex. h36m).Then how can I convert 3d joint data to h36m data. Thanks.

**Comment by dulucas** [comment]
Maybe you can train a motion prediction model with AMASS data, then detect your motion in the video using a 3D human pose model, and feed the captured motion to the trained motion prediction model to forecast your motion?
