### ISSUE TITLE
Auto-regressive motion prediction for long periods

### ISSUE THREAD

**Issue by hygenie1228** [dulucas/siMLPe#5]
Thank you for sharing the interesting work.

I want to inference the network for long-term (target_length > 25)
WACV paper denotes "During testing, we apply our model in an auto-regressive manner to generate motion for longer periods"
However, I couldn't find the auto-regressive code in this repository.
Is there any way to generate long-term motions (target_length > 25)?

**Comment by dulucas** [comment]
Hi, the auto-regressive test_function is already in the code, for example [here](https://github.com/dulucas/siMLPe/blob/30e4fc29be67d5f262285db066556549a98ff83a/exps/baseline_h36m/test.py#L31). Our model is trained to output 10 future frames, and the target length in our code is 25, thus we applied auto-regressive test to get the target length. You can get longer prediction by changing the `config.motion.h36m_target_length_train` in the config.py. Hope it helps
