### ISSUE TITLE
Pose Landmark Model

### ISSUE THREAD

**Issue by bhomaidan1990** [dulucas/siMLPe#8]
Can you please tell me where I can find the description of your Pose Landmark Model? I intend to feed your [pretrained h36m model](https://github.com/dulucas/siMLPe/tree/main/checkpoints) with poses obtained from **Mediapipe**.

So, if I just ignore the landmarks `[0, 1, 6, 11, 16, 20, 23, 24, 28, 31, 32]` ([as you did here](https://github.com/dulucas/siMLPe/blob/main/lib/datasets/h36m.py#L18)) will I be able to feed your model with mediapipe pose? or I should do further pose manipulation? thanks in advance.

![mediapipe landmarks model](https://developers.google.com/static/mediapipe/images/solutions/pose_landmarks_index.png)

**Comment by GUO-W** [comment]
Hi! H36m datasets has 32 joints:
0 Hips
1 RightUpLeg
2 RightLeg
3 RightFoot
4 RightToeBase
5 Site
6 LeftUpLeg
7 LeftLeg
8 LeftFoot
9 LeftToeBase
10 Site
11 Spine
12 Spine1
13 Neck
14 Head
15 Site
16 LeftShoulder
17 LeftArm
18 LeftForeArm
19 LeftHand
20 LeftHandThumb
21 Site
22 L_Wrist_End
23 Site
24 RightShoulder
25 RightArm
26 RightForeArm
27 RightHand
28 RightHandThumb
29 Site
30 R_Wrist_End
31 Site
And we ignored joints [0, 1, 6, 11, 16, 20, 23, 24, 28, 31].

**Comment by bhomaidan1990** [comment]
Thanks

**Comment by HitBadTrap** [comment]
Dear authors, where is the site located? (such as 5 10 15 21 29)
